version: "3.8"
services:
  nestjs-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  react-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
